### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by Nunes93** [jaseg/kimesh#2]
The erros were found on Windows 11 and Linux Mint 21.2 with KiCAD 6.0.11, KiCAD 7.08 and KiCAD 7.99 (nightly)

-------------------------------------------------------------------------------------------------
->> KiCAD 7.99 (nightly), old kimesh Plugin version, Linux:
->> when running the plugin, Generate Button doesn't do anything, with KiPython window open, shows the following error:

Traceback (most recent call last):
File "/home/user5/.local/share/kicad/7.99/scripting/plugins/kimesh/mesh_dialog.py", line 208, in generate_mesh
self.board.GetBoardPolygonOutlines(outlines,"")
File "/usr/lib/kicad-nightly/local/lib/python3.10/dist-packages/pcbnew.py", line 7959, in GetBoardPolygonOutlines
return _pcbnew.BOARD_GetBoardPolygonOutlines(self, aOutlines, aErrorHandler, aAllowUseArcsInPolygons)
TypeError: in method 'BOARD_GetBoardPolygonOutlines', argument 3 of type 'OUTLINE_ERROR_HANDLER*'
Additional information:
Wrong number or type of arguments for overloaded function ' Board_GetBoardPolygonOutlines'.
Possible C/C++ prototypes are:
BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &, OUTLINE_ERROR_HANDLER*, bool)
BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &, OUTLINE_ERROR_HANDLER*)
BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &)
- - - - - - - - - - - - - - - - - 

->> KiCAD 7.99 (nightly), newest kimesh Plugin version 2, Linux:
->> when running the plugin, never shows the plugin options menu, and display the following popup error window:

Traceback (most recent call last):
File "/home/user5/.local/share/kicad/7.99/scripting/plugins/kimesh/mesh_plugin.py", line 38, in Run
show_dialog(pcbnew.GetBoard())

File "/home/user5/.local/share/kicad/7.99/scripting/plugins/kimesh/mesh_dialog.py", line 694, in show_dialog
dialog = MeshPluginMainDialog(board)

File "/home/user5/.local/share/kicad/7.99/scripting/plugins/kimesh/mesh_dialog.py", line 79, in __init__
settings = GeneratorSettings.deserialize(f.read())

File "/home/user5/.local/share/kicad/7.99/scripting/plugins/kimesh/mesh_dialog.py", line 52, in deserialize
return cls(**d)

TypeError: GeneratorSettings.__init__() got an unexpected keyword argument
'mesh angle'
- - - - - - - - - - - - - - - - - 

->> KiCAD 7.08 (Sep 30, 2023), newest kimesh Plugin version 2, Windows:
->> when Loading Footprint Libraries from Schematic Editor, gives the following error window:

Errors were encountered loading footprints:
KiCad was unable to open this file because it was created with a more recent version than the one you are running.
To open it you will need to upgrade KiCad to a version dated 06/20/23 or later.
Full error text:
Expecting ')' in 'C:\Users\User5\Documents\project1/mesh_footprints_2wire.pretty/MeshAnchor_2W_T0.100mm_S0.100mm.kicad_mod', line 10, offset 5.
KiCad was unable to open this file because it was created with a more recent version than the one you are running.
To open it you will need to upgrade KiCad to a version dated 06/20/23 or later.
Full error text:
Expecting ')' in 'C:\Users\User5\Documents\project1/mesh_footprints_2wire.pretty/MeshAnchor_2W_T0.100mm_S0.120mm.kicad_mod', line 10, offset 5.
KiCad was unable to open this file because it was created with a more recent version than the one you are running.
To open it you will need to upgrade KiCad to a version dated 06/20/23 or later.

....etc...(for all the files from .pretty)

- - - - - - - - - - - - - - - - -

**Comment by jaseg** [comment]
Got it. Error No. 1 is because legacy kimesh doesn't work on nightly. No. 3 is because stable kicad can't read the kimesh footprints, which use KiCad's latest file format version. No.  2 is the one we should be looking at, current Kimesh on nightly. Here, it barfs because it can't read a settings file written by the older version. There's an eeasy fix for that: Just delete the `last_kimesh_settings.json` next to the `.kicad_pcb` board file. If you pull the latest version from this git repo, I added some error handling for that case and it shouldn't crash in that case anymore.

**Comment by Nunes93** [comment]
No. 1 legacy kimesh doesn't work on nightly neither stable versions (6.0.11 and 7.0.8)

No. 2 :
Deleted the `last_kimesh_settings.json` file from the project folder and installed the last version from this repo. 
When generating the mesh, continues to do nothing and gives the following error:

Traceback (most recent call last):
File "/home/User5/.local/share/kicad/7.99/scripting/plugins/kimesh-main/mesh_dialog.py", line 225, in generate_mesh
self.generate_mesh_backend(mask, anchor, net_prefix=str(self.m_net_prefix.Value), target_layer_id=target_layer_id, warn=warn, settings=settings)
File "/home/User5/.local/share/kicad/7.99/scripting/plugins/kimesh-main/mesh_dialog.py", line 280, in generate_mesh_backend
grid_x0, grid_y0 = math.floor(bbox[0]/grid_cell_width),math.floor(bbox[1]/grid_cell_width)
ValueError: cannot convert float NaN to integer

**Comment by jaseg** [comment]
That error happens when KiMesh either doesn't find the board outline, or doesn't find the mesh definition. I've got to add better error handling there. Here't two steps to resolve this:

1. Update KiMesh to the latest version from the `main` branch. I've just fixed handling of boards with no keepout zones.
2. Make sure you have both a closed board outline on the `Edge.Cuts` layer, and you have defined the mesh's shape with a filled polygon on a layer of your choosing (e.g. "User.1"). Note that KiCad's API seems to be a bit broken at the moment, and for instance plain Rectangles created with the rectangle tool do not work. You can convert other shapes to polygons by selecting them, then right clicking and choosing `Create from Selection -> Create Polygon from Selection` in the context menu. Make sure you have your mesh layer selected when you do that, since otherwise KiCad changes the polygon's layer.
